// rawColors are kept for now for easier porting of css files
const rawColors = {
  red: '#d61e1f',
  redDark: '#a71617',
  redDarker: '#860d0e',
  pink: '#fff6f3',
  grayLight: '#e0dad6',
  gray: '#9f9a97',
  grayDark: '#787573',
  grayDarker: '#312d2a',
  grayTransparent: 'rgba(159, 154, 151, 0.5)',
  black: '#323232',
  blue: '#337ab7',
  green: '#57897c',
  greenDark: '#245c4e',
  greenDarker: '#1f5145',
  lightGray: '#e2dad7',
  lightGreen: '#a4c3b9',
  greenGrey: 'rgba(181,202,194,0.8)',
  greenGreyDark: 'rgba(87,137,124,1)',
  greenBlue: 'rgba(75,192,192,1)',
  grayMedium: 'rgba(220,220,220,1)',
  greenOpaque: 'rgba(97, 175, 155, 0.7)',
  greenMist: '#d3d4cb',
  greenMistOpaque: 'rgba(211, 212, 203, 0.25)',
  facebookBlue: '#334f8d',
  twitterBlue: '#4ba2eb',
  linkedInBlue: '#006fb0',
  rssOrange: '#eb7a1d',
  pinkTransparent: 'rgba(255, 246, 243, 0)',
  blackTransparent: 'rgba(50, 50, 50, 0.6)',
  blackTransparentMin: 'rgba(0, 0, 0, 0.1)',
  whiteGray: '#eee',
  lighterShadeOfGreen: '#d4dfdB',
  silverGrey: '#dcdcdc',
};

const Roboto = "Roboto, -apple-system, BlinkMacSystemFont, 'Segoe UI', Oxygen, " +
  "Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif";
const PTSerifCaption = "'PT Serif Caption', serif";
const PTSerifRegular = "'PTSerif-Regular', serif";
const PTSerif = "'PT Serif', serif";

// Full font definitions
export const font = {
  default: `400 16px ${Roboto}`, // Default font of the whole page
  text: `400 18px/1.47 ${PTSerif}`,
  drophead: `500 32px/1.38 ${Roboto}`,
  subheadline: `700 22px/0.95 ${PTSerif}`,
  imageTitle: `700 16px/1.38 ${Roboto}`,
  leadin: `400 22px/1.55 ${PTSerifCaption}`,
  leadinSmallScreen: `400 14px/19px ${Roboto}`,
  headline: `500 42px/1.38 ${Roboto}`,
  headlineSmallScreen: `500 32px/1.38 ${Roboto}`,
  fact: `300 24px/1.38 ${Roboto}`,
  quote: `500 26px/1.38 ${Roboto}`,
  quoteMobile: `500 22px/1.38 ${Roboto}`,
  quoteAuthor: `700 22px/1.27 ${Roboto}`,
  quoteAuthorOccupation: `400 16px/1.75 ${Roboto}`,
  author: `500 18px/34px ${Roboto}`,
  authorSmall: `500 14px/25px ${Roboto}`,
  blockHeader: `300 22px ${Roboto}`,
  blockHeaderSticky: `300 20px ${Roboto}`,
  blockFooter: `500 16px ${Roboto}`,
  jobTitle: `500 16px ${Roboto}`,
  jobDescription: `500 14px/20px ${Roboto}`,
  categoryBadge: `500 14px ${Roboto}`,
  updatedText: `400 12px ${Roboto}`,
  podcastCategory: `700 14px/20px ${Roboto}`,
  defaultItemTitle: `400 16px ${Roboto}`,
  defaultArticleTitle: `500 16px/22px ${Roboto}`,
  featuredArticleTitle: `500 22px/30px ${Roboto}`,
  lessFeaturedArticleTitle: `500 18px/29px ${Roboto}`,
  smallerLessFeaturedArticleTitle: `500 18px/25px ${Roboto}`,
  articlePreviewTitleLarge: `500 18px/24px ${Roboto}`,
  articlePreviewTitleSmall: `500 14px ${Roboto}`,
  editorsChoiceTitle: `500 28px ${Roboto}`,
  editorsChoiceTitleXxl: `500 32px ${Roboto}`,
  smallerEditorsChoiceTitle: `500 18px ${Roboto}`,
  smallerEditorsChoiceTitleXxl: `500 22px ${Roboto}`,
  navMenu: `500 20px/20px ${Roboto}`,
  navMenuFit: `500 18px/18px ${Roboto}`,
  navMenuEmail: `500 12px/20px ${Roboto}`,
  navButton: `500 20px ${Roboto}`,
  subNavNutton: `400 16px ${Roboto}`,
  table: `500 14px ${Roboto}`,
  tableCellSmall: `500 12px ${Roboto}`,
  graphHeader: `300 22px ${Roboto}`,
  graphBtnTime: `300 16px ${Roboto}`,
  graphBtnTimeActive: `bold 16px ${Roboto}`,
  graphMobileBtnTime: `300 14px ${Roboto}`,
  graphMobileBtnTimeActive: `bold 14px ${Roboto}`,
  graphBtnData: `500 14px ${Roboto}`,
  footerLink: `700 16px ${Roboto}`,
  footerContact: `500 12px/24px ${Roboto}`,
  footerBottom: `500 12px ${Roboto}`,
  footerUpButton: `600 14px ${Roboto}`,
  searchInput: `400 20px ${Roboto}`,
  searchInputPlaceholder: `italic 300 20px ${Roboto}`,
  searchButton: `500 20px ${Roboto}`,
  sideMenuItem: `500 20px ${Roboto}`,
  articleHeaderInfo: `400 14px/21px ${Roboto}`,
  articleHeaderLabel: `500 14px/30px ${Roboto}`,
  relatedArticleDate: `14px ${Roboto}`,
  articleTags: `400 16px/30px ${Roboto}`,
  authenticationCTAMessageUpper: `600 22px/22px ${Roboto}`,
  authenticationCTAMessageLower: `600 18px/22px ${Roboto}`,
  toomasWidgetButton: `500 16px ${Roboto}`,
  toomasWidgetButtonMobile: `500 14px ${Roboto}`,
  toomasWidgetButtonMobileSmall: `500 12px ${Roboto}`,
  toomasInfoTitle: `500 56px ${Roboto}`,
  toomasPortfolioItemTitle: `500 24px ${Roboto}`,
  toomasHeaderTitle: `700 64px ${Roboto}`,
  toomasHeaderDescription: `700 16px ${Roboto}`,
  radioWidgetShow: `400 14px ${Roboto}`,
  button: `400 16px ${Roboto}`,
  eventTitle: `600 16px ${Roboto}`,
  eventDescription: `400 14px ${Roboto}`,
  specialPubListChapter: `400 14px ${Roboto}`,
  specialPubChapterTitle: `600 18px ${Roboto}`,
  newsletterTitle: `300 18px ${Roboto}`,
  newsletterTitleBold: `500 22px ${Roboto}`,
  newsletterText: `500 16px ${Roboto}`,
  newsletterInput: `400 18px ${Roboto}`,
  tagWidgetTitle: `700 30px ${Roboto}`,
  tagWidgetDescription: `400 18px ${Roboto}`,
  subscriptionAreaTitle: `500 27px/1.3 ${Roboto}`,
  paymentMethodChoice: `500 14px/1.42 ${Roboto}`,
  additionalPaymentMethods: `300 13px/13px ${Roboto}`,
  radioShow: `500 18px ${Roboto}`,
  cookieConsentBar: `400 16px/24px ${Roboto}`,
  number: `900 26px/36px ${Roboto}`,
  numberText: `300 26px/36px ${Roboto}`,
  searchResultCategoryName: `500 16px ${Roboto}`,
  searchResultPublishDate: `500 16px ${Roboto}`,
  searchResultHeadline: `300 22px ${Roboto}`,
  searchResultLeadin: `normal 14px/22px ${PTSerifRegular}`,
  specialPublicationPackageTitle: `500 21px/normal ${Roboto}`,
  specialPublicationChapterLink: `500 16px/1.38 ${Roboto}`,
  specialPublicationToCChapters: `300 22px/normal ${Roboto}`,
  specialPublicationToCTitle: `300 14px/1.71 ${Roboto}`,
  specialPublicationToCTitleActive: `500 16px/1.5 ${Roboto}`,
  specialPublicationMobileChapterTitle: `500 14px/1.36 ${Roboto}`,
  specialPublicationMobileChaptersHeader: `300 18px/50px ${Roboto}`,
  indexNumber: `700 20px ${Roboto}`,
  largeScreenLeadin: `400 18px/25px ${Roboto}`,
  articleInfoBank: `500 16px/26px ${Roboto}`,
};

export const icon = {
  medium: '16px',
  large: '18px',
  xlarge: '20px',
  xxlarge: '30px',
  xxxlarge: '34px',
  footerUp: '35px',
  logoSmall: '100px',
  logo: '120px',
  closeToomasWidget: '40px',
  paywallKeyIcon: '60px',
  specialPubChapterChevron: '48px',
  specialPubChapterChevronMobile: '28px',
};

export const color = {
  primary: rawColors.red,
  primaryDark: rawColors.redDark,
  primaryDarker: rawColors.redDarker,
  secondary: rawColors.green,
  secondaryDark: rawColors.greenDark,
  secondaryLight: rawColors.lightGreen,
  secondaryLighter: rawColors.lighterShadeOfGreen,
  pageBackground: rawColors.pink,
  titleText: rawColors.grayDarker,
  newsImageBackground: rawColors.blackTransparentMin,
  newsImageIcon: rawColors.blackTransparent,
  link: rawColors.green,
  border: rawColors.lightGray,
  text: rawColors.black,
  imageTitle: rawColors.gray,
  appBackground: rawColors.pink,
  dataButton: rawColors.pink,
  graphBackground: rawColors.greenGrey,
  graphBorder: rawColors.greenGreyDark,
  graphPointBorder: rawColors.greenBlue,
  graphPointHoverBackground: rawColors.greenBlue,
  graphPointHoverBorder: rawColors.grayMedium,
  graphDetailsBackground: rawColors.pink,
  accountButtonBackground: rawColors.grayDarker,
  graphBtnText: rawColors.black,
  graphHeaderUnderline: rawColors.gray,
  graphBtnUnderline: rawColors.black,
  graphBtnDataLightBackGround: rawColors.grayLight,
  graphBtnDataDarkBackGround: rawColors.grayDark,
  graphBtnDataActiveBackGround: rawColors.greenMist,
  graphGridLine: rawColors.greenMist,
  graphBtnDataBorder: rawColors.greenMist,
  tableRowDark: rawColors.greenMistOpaque,
  tableHeadBackground: rawColors.greenMist,
  tablePositive: rawColors.green,
  tableNegative: rawColors.red,
  tableNAText: rawColors.gray,
  tableSortInactive: rawColors.gray,
  tableSortActive: rawColors.black,
  tableLoadingText: rawColors.grayDark,
  tableOverflowIndicator: rawColors.pinkTransparent,
  tableOpenedColumnName: rawColors.grayDark,
  quoteBackground: rawColors.greenMistOpaque,
  footerLink: rawColors.grayDarker,
  footerUpButton: rawColors.grayDarker,
  articleHeaderCategory: rawColors.greenMistOpaque,
  articleHeaderIcon: rawColors.gray,
  facebook: rawColors.facebookBlue,
  twitter: rawColors.twitterBlue,
  linkedin: rawColors.linkedInBlue,
  rss: rawColors.rssOrange,
  email: rawColors.gray,
  'share-2': rawColors.grayDark,
  separator: rawColors.lightGray,
  paywallKeyIcon: rawColors.green,
  investor: rawColors.green,
  toomasWidgetBody: rawColors.lightGray,
  closeToomasWidget: rawColors.green,
  itemListText: rawColors.grayDarker,
  iconDefault: rawColors.grayDark,
  button: rawColors.green,
  buttonDark: rawColors.greenDark,
  eventDescription: rawColors.grayDark,
  jobDescription: rawColors.grayDark,
  newsletterPrimary: rawColors.green,
  newsletterSecondary: rawColors.greenDark,
  newsletterError: rawColors.red,
  paywallAreaBackground: rawColors.lightGreen,
  checkboxBorder: rawColors.lightGray,
  checkmark: rawColors.green,
  modalBackground: rawColors.blackTransparent,
  paymentMethodChoiceBackground: rawColors.whiteGray,
  subscriptionError: rawColors.red,
  modalCloseHover: rawColors.blue,
  radioShowTime: rawColors.gray,
  radioCurrentIcon: rawColors.red,
  cookieBarBackground: rawColors.lighterShadeOfGreen,
  specialPublicationHeaderBorder: rawColors.grayTransparent,
  specialPublicationChapter: rawColors.gray,
  specialPublicationToCOpened: rawColors.green,
  specialPubBackground: rawColors.pinkTransparent,
  specialPublicationToCChaptersBorder: rawColors.grayLight,
  specialPublicationActiveToCPreview: rawColors.green,
  specialPublicationMobileChaptersHeader: rawColors.black,
  specialPublicationMobileChaptersBorder: rawColors.grayTransparent,
  specialPublicationChapterListBorder: rawColors.greenMist,
  specialPublicationChapterListShadow: rawColors.greenOpaque,
  buttonReportComment: rawColors.gray,
  commentTimestamp: rawColors.gray,
  articleInfoBankBorder: rawColors.silverGrey,
  formValidationError: rawColors.red,
};

export const aripaevNavTheme = {
  primary: rawColors.red,
  primaryDark: rawColors.redDark,
};

export const investorNavTheme = {
  primary: rawColors.green,
  primaryDark: rawColors.greenDark,
};

export const marketingBannerTheme = {
  primary: color.secondaryLight,
  secondary: color.secondaryLighter,
  button: color.secondary,
};

export const margin = {
  xsmall: '5px',
  small: '10px',
  medium: '15px',
  large: '20px',
  xlarge: '30px',
  xxlarge: '35px',
  xxxlarge: '40px',
};

export const widths = {
  content: '1200px',
  adContent: '1140px',
};

// z-index stacking of items
export const stack = {
  cookieBar: 1003,
  modalContent: 1002,
  modalOverlay: 1001,
  imageGallery: 1000,
  sideMenu: 99,
  topBar: 98,
  desktopMenu: 90,
  specialPubToCOverlay: 90,
  accountMenu: 2,
  investorTraderWidget: 2,
  dropDown: 1,
  loadingCell: 1,
  tableOverflow: 1,
};
