const fontFallback = "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Open Sans', 'Helvetica Neue', sans-serif";

export const Fonts = {
  default: `400 16px AktivGroteskCorp-Regular, ${fontFallback}`, // Default font of the whole page
  defaultTitle: `400 14px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  articleText: `400 16px/26px AktivGroteskCorp-Regular, ${fontFallback}`,
  articleSubHeadline: `600 24px/26px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleFactTitle: `700 18px/26px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleFact: `700 16px/22px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleQuoteText: `700 26px/38px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleQuoteTextMobile: `600 22px/30px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleQuoteAuthor: `700 18px/36px AktivGroteskCorp-Bold, ${fontFallback}`,
  articleQuoteSymbol: `700 100px/0 AktivGroteskCorp-Bold, ${fontFallback}`,
  footerRegular: `400 14px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  footerMedium: `500 14px/22px AktivGroteskCorp-Medium, ${fontFallback}`,
  headerLogo: `600 18px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  headerLink: `500 16px/22px AktivGroteskCorp-Medium, ${fontFallback}`,
  medium: `400 14px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  small: `400 11px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  title: `600 40px/53px AktivGroteskCorp-Bold, ${fontFallback}`,
  leadIn: `400 22px/30px AktivGroteskCorp-Medium, ${fontFallback}`,
  landingArticleTitleLarge: `600 40px/50px AktivGroteskCorp-Bold, ${fontFallback}`,
  landingArticleTitleLargeMobile: `600 28px/34px AktivGroteskCorp-Bold, ${fontFallback}`,
  landingArticleTitleSmall: `600 22px/30px AktivGroteskCorp-Bold, ${fontFallback}`,
  landingArticleTitleSmallMobile: `600 18px/24px AktivGroteskCorp-Bold, ${fontFallback}`,
  landingArticleDate: `400 12px/16px AktivGroteskCorp-Regular, ${fontFallback}`,
  listDate: `400 12px/12px AktivGroteskCorp-Regular, ${fontFallback}`,
  categoryBadge: `500 12px/16px AktivGroteskCorp-Medium, ${fontFallback}`,
  blockTitle: `500 30px/26px AktivGroteskCorp-Medium, ${fontFallback}`,
  blockTitleMobile: `500 22px/26px AktivGroteskCorp-Medium, ${fontFallback}`,
  blockFooter: `400 22px/32px AktivGroteskCorp-Regular, ${fontFallback}`,
  tag: `400 11px/18px AktivGroteskCorp-Regular, ${fontFallback}`,
  tagMobile: `400 11px/22px AktivGroteskCorp-Regular, ${fontFallback}`,
  newsletterDefault: `400 14px/26px AktivGroteskCorp-Regular, ${fontFallback}`,
  newsletterTitle: `500 18px/26px AktivGroteskCorp-Medium, ${fontFallback}`,
  newsletterSubmitButton: `400 22px/32px AktivGroteskCorp-Regular, ${fontFallback}`,
  newsletterPrivacyLabel: `500 12px/26px AktivGroteskCorp-Medium, ${fontFallback}`,
  radioHeadline: `500 18px/22px AktivGroteskCorp-Medium, ${fontFallback}`,
  radioSubHeadline: `400 12px/20px AktivGroteskCorp-Regular, ${fontFallback}`,
  relatedBlockHeader: `500 16px/26px AktivGroteskCorp-Medium, ${fontFallback}`,
  relatedArticleTitle: `600 16px/22px AktivGroteskCorp-Bold, ${fontFallback}`,
  relatedArticleTitleMobile: `600 16px/20px AktivGroteskCorp-Bold, ${fontFallback}`,
  table: `500 14px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableCellSmall: `500 12px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchButton: `500 16px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchInput: `500 16px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchInputPlaceholder: `italic 400 16px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchButtonMobile: `500 14px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchInputMobile: `500 14px AktivGroteskCorp-Regular, ${fontFallback}`,
  tableSearchInputPlaceholderMobile: `italic 400 14px AktivGroteskCorp-Regular, ${fontFallback}`,
  imageDescription: `400 12px AktivGroteskCorp-Medium, ${fontFallback}`,
  mobileMenuItems: `400 18px/50px AktivGroteskCorp-Medium, ${fontFallback}`,
};

const rawColors = {
  white: '#fff',
  black: '#000',
  red: 'red',
  lightYellow: '#fffeef',
  grayLight: '#e0dad6',
  grayDark: '#787573',
};

export const Colors = {
  text: rawColors.black,
  textGray: '#717171',
  textWhite: rawColors.white,
  link: rawColors.black,
  linkHover: '#333',
  background: rawColors.white,
  iduFirmaYellow: '#ffce00',
  supporterYellow: '#FFFDEF',
  dateGray: '#868686',
  arrowWhite: rawColors.white,
  buttonBlack: rawColors.black,
  error: rawColors.red,
  unsubscribeBackground: rawColors.lightYellow,
  tableRowDark: '#d3d4cb',
  tableHeadBackground: 'rgba(211, 212, 203, 0.25)',
  tablePositive: rawColors.green,
  tableNegative: rawColors.red,
  tableNAText: rawColors.gray,
  tableSortInactive: rawColors.gray,
  tableSortActive: rawColors.black,
  tableLoadingText: rawColors.grayDark,
  tableOverflowIndicator: rawColors.grayLight,
  tableOpenedColumnName: rawColors.grayDark,
  imageDescription: '#555555',
};

export const size = {
  contentWidth: '1120px',
  articleLeftSideWidth: '760px',
  icon: '34px',
  iconSmall: '17px',
};

export const margin = {
  xsmall: '5px',
  small: '10px',
  medium: '15px',
  large: '20px',
  xlarge: '30px',
  xxlarge: '35px',
  xxxlarge: '40px',
  xxxxlarge: '50px',
};

export default {
  Fonts,
  Colors,
  margin,
  size,
};
